# Generated by Django 2.0.5 on 2018-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'Login',
                'managed': True,
            },
        ),
    ]
