# Generated by Django 2.0.5 on 2018-05-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtsolicitacao', models.DateTimeField(blank=True, db_column='DtSolicitacao', null=True)),
                ('idcoordenador', models.IntegerField(blank=True, db_column='IdCoordenador', null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('idaluno', models.ForeignKey(db_column='IdAluno', on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.Aluno')),
            ],
            options={
                'db_table': 'SolicitacaoMatricula',
                'managed': True,
            },
        ),
    ]
