from .alunos import Aluno
from .disciplinas import Disciplina
from .atividades import Atividade 
from .atividadevinculadas import Atividadevinculada 
from .coordenadores import Coordenador 
from .cursos import Curso
from .disciplinas import Disciplina
from .disciplinas_ofertadas import DisciplinaOfertada
from .entregas import Entrega
from .mensagens import Mensagem
from .professores import Professor
from .solicitacao_matriculas import SolicitacaoMatricula
from .sessaoAluno import SessaoAluno