# Generated by Django 2.0.4 on 2018-05-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadevinculada',
            name='iddisciplinaofertada',
            field=models.ForeignKey(db_column='IdDisciplinaOfertada', on_delete=django.db.models.deletion.DO_NOTHING, to='disciplinas.DisciplinaOfertada'),
        ),
        migrations.AlterField(
            model_name='solicitacaomatricula',
            name='iddisciplinaofer',
            field=models.ForeignKey(db_column='IdDisciplinaOfer', on_delete=django.db.models.deletion.DO_NOTHING, to='disciplinas.DisciplinaOfertada'),
        ),
    ]
