# Generated by Django 2.0.4 on 2018-05-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadevinculada',
            old_name='iddisciplinaofertada',
            new_name='iddisciplinaOfertada',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='atividadevinculada',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disciplinaofertada',
            name='idcurso',
            field=models.ForeignKey(db_column='IdCurso', on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.Curso'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
